server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root123456

  application:
    name: MybatisDemo
  redis:
    host: 127.0.0.1
    port: 6379
#    database: 0
    password: root123456
    lettuce:
      pool:
        #连接池最大连接数(使用负值表示没有限制)
        max-active: 8
        # 连接池中的最大空闲连接 默认 8
        max-idle: 8
        #连接池中的最小空闲连接 默认 0
        min-idle: 0
        # 连接池最大阻塞等待时间(使用负值表示没有限制)
        max-wait: -1

mybatis:
  mapper-locations: classpath:mappers/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

  activiti:
    database-schema-update: true